###############################################################################
## System Logger  https://www.home-assistant.io/components/logger
## levels: debug, fatal, critical, error, warning, warn, info, notset
###############################################################################
default: warn
filters:
  pybalboa.balboa:
    - "Cannot connect to spa at 192.168.1.125:4257" #ERROR (MainThread) [pybalboa.balboa] Cannot connect to spa at 192.168.1.125:4257
    - "Spa stopped responding, requesting panel config" #ERROR (MainThread) [pybalboa.balboa] Spa stopped responding, requesting panel config.
    - "Lost connection to spa, attempting reconnect" #ERROR (MainThread) [pybalboa.balboa] Lost connection to spa, attempting reconnect.
    - "Error connecting to spa" #ERROR (MainThread) [pybalboa.balboa] Error connecting to spa at 192.168.1.125:4257: [Errno 110] Connect call failed ('192.168.1.125', 4257)
    - "Connection reset by peer" #ERROR (MainThread) [pybalboa.balboa] Connection reset by peer
    - "Message had bad CRC" #ERROR (MainThread) [pybalboa.balboa] Message had bad CRC, discarding
    - "Spa unreachable" #ERROR (MainThread) [pybalboa.balboa] Spa unreachable
    - "Spa sent an unknown message" #ERROR (MainThread) [pybalboa.balboa] Spa sent an unknown message: 7e17ffaf26008700000002000001000000000000000000087e
    - "Spa read failed" #ERROR (MainThread) [pybalboa.balboa] Spa read failed: 0 bytes read on a total of 2 expected bytes
    - "Error sending message: Connection lost" #ERROR (MainThread) [pybalboa.balboa] Error sending message: Connection lost
  custom_components.balboa.const: # homeassistant.components.balboa.const:
    - "Failed to connect to spa" #ERROR (MainThread) [homeassistant.components.balboa.const] Failed to connect to spa at 192.168.1.125
  pychromecast.socket_client:
    - "Heartbeat timeout, resetting connection" #WARNING (Thread-26) [pychromecast.socket_client] [Laundry Room Speaker(192.168.1.197):8009] Heartbeat timeout, resetting connection
    - "Failed to connect to service" #ERROR (Thread-26) [pychromecast.socket_client] [Laundry Room Speaker(192.168.1.197):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.1.197', 8009)), retrying in 5.0s
    - "Error reading from socket" #ERROR (Thread-9) [pychromecast.socket_client] [Bedroom Hub(192.168.1.194):8009] Error reading from socket.
    - "Error communicating with socket, resetting connection" #WARNING (Thread-9) [pychromecast.socket_client] [Bedroom Hub(192.168.1.194):8009] Error communicating with socket, resetting connection
  homeassistant.helpers.entity: # always takes more than 10 seconds
    - "Update of sensor.speedtest_download is taking over 10 seconds"
    - "Updating state for" #WARNING (MainThread) [homeassistant.helpers.entity] Updating state for sensor.pirateweather_liquid_accumulation_4h (<class 'custom_components.pirateweather.sensor.PirateWeatherSensor'>) took 2.788 seconds. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues
    # homeassistant.components.roku.coordinator: # WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.speedtest_download is taking over 10 seconds
    #   - "Error fetching roku data" #ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
  homeassistant.components.mold_indicator.sensor: # triggered when templates are reloaded
    - "Unable to parse temperature sensor sensor.outdoor_temperature with state: unavailable" #ERROR (MainThread) [homeassistant.components.mold_indicator.sensor] Unable to parse temperature sensor sensor.outdoor_temperature with state: unavailable
  # custom_components.frigate.api: #TEMP until fix
  #   - "Timeout error fetching information" #ERROR (MainThread) [custom_components.frigate.api] Timeout error fetching information from http://ccab4aaf-frigate-fa:5000/api/stats:
  # custom_components.frigate: #TEMP until fix
  #   - "Error fetching frigate data" #ERROR (MainThread) [custom_components.frigate] Error fetching frigate data:
  custom_components.nest_protect: #TEMP until fix
    # - "504 error while authenticating" #ERROR (MainThread) [custom_components.nest_protect] 504 error while authenticating - . Please create an issue on GitHub.
    - "Unknown exception." #ERROR (MainThread) [custom_components.nest_protect] Unknown exception. Please create an issue on GitHub with your logfile. Updates paused for 5 minutes.
    - "Unknown pynest exception." # ERROR (MainThread) [custom_components.nest_protect] Unknown pynest exception. Please create an issue on GitHub with your logfile. Updates paused for 1 minute.
  # custom_components.nest_protect.pynest: #TEMP until fix
  #   - "Authentication error: invalid_request" #ERROR (MainThread) [custom_components.nest_protect.pynest] Authentication error: invalid_request
  #   - "Could not interpret Nest response" #ERROR (MainThread) [custom_components.nest_protect.pynest] Could not interpret Nest response
  # homeassistant.util.logging:
  #   - "Exception in state_message_received when handling msg on 'wyzebridge" #ERROR (MainThread) [homeassistant.util.logging] Exception in state_message_received when handling msg on 'wyzebridge/charlie-crate/alarm': '0'
  # homeassistant.components.hassio.handler:
  #   - "Client error on /addons/7094bb28_docker-wyze-bridge/changelog request 0" #ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /addons/7094bb28_docker-wyze-bridge/changelog request 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream', url=URL('http://172.30.32.2/addons/7094bb28_docker-wyze-bridge/changelog')
  # homeassistant.components.hassio.data:
  #   - "Could not fetch changelog for 7094bb28_docker-wyze-bridge" #WARNING (MainThread) [homeassistant.components.hassio.data] Could not fetch changelog for 7094bb28_docker-wyze-bridge:
  homeassistant.components.fully_kiosk:
    - "Error fetching 192.168.1.70 data" #ERROR (MainThread) [homeassistant.components.fully_kiosk] Error fetching 192.168.1.70 data: (500, "Remote admin server can't find a running Fully activity...")
    - "Error requesting 192.168.1.70 data" #ERROR (MainThread) [homeassistant.components.fully_kiosk] Error requesting 192.168.1.70 data: Cannot connect to host 192.168.1.70:2323 ssl:False [Connect call failed ('192.168.1.70', 2323)]
  fullykiosk:
    - "Invalid response from Fully Kiosk Browser API" #WARNING (MainThread) [fullykiosk] Invalid response from Fully Kiosk Browser API: 500
  # homeassistant.components.websocket_api.http.connection: #TEMP until resolved
  # - "Unexpected exception" #ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [281472405390672] Unexpected exception
  homeassistant.components.media_player:
    - "Updating webostv media_player took longer than the scheduled update interval" # WARNING (MainThread) [homeassistant.components.media_player] Updating webostv media_player took longer than the scheduled update interval 0:00:10
  homeassistant.components.uptimerobot:
    - "Error fetching uptimerobot data" #ERROR (MainThread) [homeassistant.components.uptimerobot] Error fetching uptimerobot data: Request timeout for 'https://api.uptimerobot.com/v2/getMonitors'
